project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "index.qmd"
    - "analyses/*.qmd"
    - "eda/*.qmd"

website:
  sidebar:
    style: "floating"
    search: true
    align: left
    contents:
      - text: "ASCOT Anticoagulation"
        file: index.qmd
      - section: "EDA"
        contents:
          - eda/data-overview.qmd
          - analyses/patient_disposition.qmd
      - section: "Outcomes"
        contents:
          - analyses/primary_outcome.qmd
          - analyses/all_cause_mortality.qmd
          - analyses/who_ordinal_scale.qmd

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    fig-align: center
    captions: true
    cap-location: margin
    table-captions: true
    tbl-cap-location: margin
    reference-location: margin
    theme: journal
    fontsize: 1em
    self-contained: true
    standalone: true
    code-tools: true
    code-fold: true
    code-link: false

execute:
  warning: false
  message: false
  echo: true
  freeze: auto

engine: knitr
