project:
  type: default
  output-dir: docs
  execute-dir: project
  render:
    - "analyses/*.qmd"
    - "eda/*.qmd"

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    fig-align: center
    captions: true
    cap-location: margin
    table-captions: true
    tbl-cap-location: margin
    reference-location: margin
    theme: journal
    fontsize: 1em
    self-contained: true
    standalone: true
    code-tools: true
    code-fold: true
    code-link: false

execute:
  warning: false
  message: false
  echo: true

engine: knitr
