project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "index.qmd"
    - "analyses/*.qmd"
    - "eda/*.qmd"

website:
  sidebar:
    title: ASCOT Anticoagulation Analyses
    style: "floating"
    search: true
    align: left
    contents:
      - text: "Summary"
        file: index.qmd
      - section: "Overview and Baseline"
        contents:
          - eda/data-overview.qmd
          - eda/patient-disposition.qmd
          - eda/baseline-summaries.qmd
      - section: "Outcomes"
        contents:
          - analyses/primary_outcome.qmd
          - "analyses/7-1_time_to_clinical_recovery.qmd"
          - "analyses/7-2_who_ordinal_scale.qmd"
          - "analyses/7-3_all_cause_mortality.qmd"
          - "analyses/7-4_days_alive_hospital_free.qmd"

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    fig-align: center
    captions: true
    cap-location: margin
    table-captions: true
    tbl-cap-location: margin
    reference-location: margin
    theme: journal
    fontsize: 1em
    self-contained: true
    standalone: true
    code-tools: true
    code-fold: true
    code-link: false

execute:
  warning: false
  message: false
  echo: true
  freeze: auto

engine: knitr
